### ISSUE TITLE
Acompanhamento de desenvolvimento do Cidade Dorme

### ISSUE THREAD

**Issue by leogianfagna** [leogianfagna/IssueTracker#217]
### TO-DO
- [x] Sair da region tira o player head
- [x] Para votar precisa estar na region de jogar, main region para camarote não votar
- [x] Camarote: Imune a cegueira, não fala, region com prioridade
- [x] Mortos não votam
- [x] Mensagem em eliminação errada

> Batata:

Como sortear cada pessoa? Podendo usar chatgpt ou outros métodos de sorteio.
Como fazer o ciclo da noite: Colocar a mesma tela preta usada no guarda roupa para todos até o período da noite saia ou efeito de cegueira(cegueira por efeito de warden dependendo da versão não atinge a pessoa corretamente).
Aonde as pessoas permanecerem, serão bloqueadas de se movimentar para evitar o caos tendo limite de jogadores. Muitas pessoas será uma baderna para organizar além de apenas dificuldade e atrasar o jogo.
Mestre:
Irá comunicar todos de maneira fácil sendo por tell quem acabou morrendo ou foi morto. 
Além de comunicar quem morreu, será visível quem acabou morrendo caso o efeito de deixar rastejando seja possível. Caso não seja possível, adicionar efeito de glowing possa auxiliar e facilitar.
Anjo:
Detetive:
Após um jogador tenha sido morto, ele irá perder o efeito de cegueira podendo agir para tentar identificar algum dos assassino além de comunicar no chat para todos.
Assassino:
Tentar criar um chat em especifico para eles se comunicarem de maneira mais clara. Como fazer isso? Talvez travar chat entre as pessoas ou até mesmo colocar elas em grupo para se comunicarem. 
Assassinos ficam com efeito de cegueira e bloqueados de falar em chat aberto após receberem o efeito de cegueira podendo decidir quem irão matar. 
Cidadão:
Podemos deixar todos em pé. Pessoas que acabarem morrendo recebem o comando de permanecer rastejando significando que estão mortos. Caso não funcione, adicionar efeito de glowing na pessoa.
Acho que a cada 4 pessoas, terá 1 assassino e 1 médico
