### ISSUE TITLE
Novos bugs no AdvancedEnchantments

### ISSUE THREAD

**Issue by leogianfagna** [leogianfagna/IssueTracker#273]
- [x] A descrição por nível magicamente parou de funcionar https://github.com/GC-spigot/AdvancedEnchantments/issues/4006

- [x] Bug do toque suave https://github.com/GC-spigot/AdvancedEnchantments/issues/4005

- [ ] Placeholder não funciona no menu https://github.com/GC-spigot/AdvancedEnchantments/issues/4010

- [x] Essência da mudança não funciona https://github.com/GC-spigot/AdvancedEnchantments/issues/3975

Bônus. Esse bug ao abrir o **Tinkerer** https://mclo.gs/UfKQACv
