### ISSUE TITLE
Masmorras

### ISSUE THREAD

**Issue by leogianfagna** [leogianfagna/IssueTracker#44]
Descrição: A nova atualização do Henesys 1.0 em trazer duelos em masmorras contra mobs.

# Bugs
- [x] Se acaba antes, mobs continuam a ser spawnados (SOLUÇÃO, contrar flag de mobspawn no jogo)
- [x] Comando que vai limpar todas as entidades (executar na hora de finalizar? Mas acho que se não tiver renderizado não rola)
- [x] Comando desconhecido ainda ao iniciar
- [x] Subir as paredes

# TO-DO
## últimos detalhes
- [x] Criação da categoria Sinistra
- [x] Novos encantamentos dessa categoria
- [x] Datas marcadas

## Criação
- [x] Elaborar a forma de entrar no evento
- [x] Fazer as mensagens de eventos
- [x] Setar destinos
- [x] Bloquear CommandBlock de todos os mundos fora o arenas
- [x] Habilitar command block para funcionar
- [x] Criar o comando no Mycommand para trocar os itens do bosshop
- [x] Linkar o comando com o bossshop
- [x] Testar as trocas
- [x] Pensar na entrega de pedras
- [x] Cooldown no comando de finalizar mobarena
- [x] Bloquear itens como pérola do fim, elytra, etc
- [x] Barreiras para não subir nas estacas
- [x] Holograma de finalizar
- [x] Criar bloco, vai ter que executar como a pessoa para ninguém conseguir fazer de fora

## Entrega de recompensas
- [x] Criar variável global mobarena_vencida
- [x] Setar player data "mobarena_participado" ao sair do evento para o dia do ANO
- [x] Criar ícone de recompensa de dungeon que confere se "mobarena_participado" e "mobarena_vencida" condizem
- [x] Setar recompensas no ícone

## Criar comando de finalizar mobarena
- [x] Setar "mobarena_vencida" como localtime do dia do ANO
- [x] Como proteger de finalizar ANTES de começar?

# Comandos que geram mobs
Usar os modificadores no summon de mobs. O comando fica bem grande dando apenas para fazer pelo console. Possivelmente, esse sistema terá que ser feito usando COMMANDBLOCK.

### Servo gnomo
```
execute in minecraft:mundoeventos run summon zombie -217 64 -344 {IsBaby:1,CustomName:'[{"text":"Servo Gnomo","color":"dark_green"}]',Health:50,ArmorItems:[{id:leather_boots,tag:{Unbreakable:1,display:{color:6205718},AttributeModifiers:[{AttributeName:"generic.armor",Amount:150,Name:"generic.armor",UUID:[I;-1231021,30274,104821,-60548]}],Enchantments:[{id:vanishing_curse,lvl:1},{id:thorns,lvl:3}]},Count:1},{id:leather_leggings,tag:{Unbreakable:1,display:{color:6205718},AttributeModifiers:[{AttributeName:"generic.armor",Amount:150,Name:"generic.armor",UUID:[I;-1231021,30274,104821,-60548]}],Enchantments:[{id:vanishing_curse,lvl:1},{id:thorns,lvl:3}]},Count:1},{id:leather_chestplate,tag:{Unbreakable:1,display:{color:6205718},AttributeModifiers:[{AttributeName:"generic.armor",Amount:150,Name:"generic.armor",UUID:[I;-1231021,30274,104821,-60548]}],Enchantments:[{id:vanishing_curse,lvl:1},{id:thorns,lvl:3}]},Count:1},{id:leather_helmet,tag:{Unbreakable:1,display:{color:6205718},AttributeModifiers:[{AttributeName:"generic.armor",Amount:150,Name:"generic.armor",UUID:[I;-1231021,30274,104821,-60548]}],Enchantments:[{id:vanishing_curse,lvl:1},{id:thorns,lvl:3}]},Count:1}],Attributes:[{Name:"generic.attack_knockback",Base:70f},{Name:"generic.movement_speed",Base:0.5f},{Name:"generic.armor_toughness",Base:20f},{Name:"generic.attack_damage",Base:30f},{Name:"generic.max_health",Base:50f}],ArmorDropChances:[0f,0f,0f,0f]}
```

### Servo pai
```
execute in minecraft:mundoeventos run summon zombie -217 64 -344 {CustomName:'[{"text":"Servo pai","color":"dark_green"}]',Health:60,ArmorItems:[{id:leather_boots,tag:{Unbreakable:1,display:{color:6205718},AttributeModifiers:[{AttributeName:"generic.armor",Amount:150,Name:"generic.armor",UUID:[I;-1231021,30274,104821,-60548]}],Enchantments:[{id:vanishing_curse,lvl:1},{id:thorns,lvl:3}]},Count:1},{id:leather_leggings,tag:{Unbreakable:1,display:{color:6205718},AttributeModifiers:[{AttributeName:"generic.armor",Amount:150,Name:"generic.armor",UUID:[I;-1231021,30274,104821,-60548]}],Enchantments:[{id:vanishing_curse,lvl:1},{id:thorns,lvl:3}]},Count:1},{id:leather_chestplate,tag:{Unbreakable:1,display:{color:6205718},AttributeModifiers:[{AttributeName:"generic.armor",Amount:150,Name:"generic.armor",UUID:[I;-1231021,30274,104821,-60548]}],Enchantments:[{id:vanishing_curse,lvl:1},{id:thorns,lvl:3}]},Count:1},{id:leather_helmet,tag:{Unbreakable:1,display:{color:6205718},AttributeModifiers:[{AttributeName:"generic.armor",Amount:150,Name:"generic.armor",UUID:[I;-1231021,30274,104821,-60548]}],Enchantments:[{id:vanishing_curse,lvl:1},{id:thorns,lvl:3}]},Count:1}],Attributes:[{Name:"generic.attack_knockback",Base:70f},{Name:"generic.movement_speed",Base:0.3f},{Name:"generic.armor_toughness",Base:20f},{Name:"generic.attack_damage",Base:40f},{Name:"generic.max_health",Base:60f}],ArmorDropChances:[0f,0f,0f,0f]}
```

### Protetor do caixão
```
execute in minecraft:mundoeventos run summon skeleton -217 64 -344 {CustomName:'[{"text":"Protetor do caixão"}]',Health:200,HandItems:[{id:bow,tag:{Enchantments:[{id:vanishing_curse,lvl:1},{id:power,lvl:10},{id:punch,lvl:10}]},Count:1}],HandDropChances:[f],Attributes:[{Name:"generic.max_health",Base:200f}]}
```
### Rachador de crânios
```
execute in minecraft:mundoeventos run summon vindicator -217 64 -344 {CustomName:'[{"text":"Rachador de Crânios","color":"dark_gray"}]',HandItems:[{id:netherite_axe,tag:{AttributeModifiers:[{AttributeName:"generic.attack_damage",Amount:100,Name:"generic.attack_damage",UUID:[I;-1231017,2029,172658,-4058]}],Enchantments:[{id:sharpness,lvl:5}]},Count:1}],HandDropChances:[0f]}
```
### Kravana
```
execute in minecraft:mundoeventos run summon husk -217 64 -344 {CustomName:'[{"text":"Kravana","color":"gold"}]',Health:400,HandItems:[{id:netherite_axe,tag:{AttributeModifiers:[{AttributeName:"generic.attack_speed",Amount:40,Name:"generic.attack_speed",UUID:[I;-1231021,4697,111025,-9394]},{AttributeName:"generic.attack_damage",Amount:100,Name:"generic.attack_damage",UUID:[I;-1231021,4797,111025,-9594]}],Enchantments:[{id:vanishing_curse,lvl:1},{id:power,lvl:10},{id:punch,lvl:10},{id:sharpness,lvl:5}]},Count:1}],HandDropChances:[f],Attributes:[{Name:"generic.attack_speed",Base:81f},{Name:"generic.movement_speed",Base:0.5f},{Name:"generic.max_health",Base:400f}]}
```
### Líder final
```
execute in minecraft:mundoeventos run summon zombie_horse -217 64 -344 {SaddleItem:{id:saddle,Count:1},Health:2000,Attributes:[{Name:"generic.movement_speed",Base:0.5f},{Name:"generic.max_health",Base:2000f}],Passengers:[{id:husk,CustomName:'[{"text":"Líder","color":"red"}]',Health:3000,active_effects:[{id:resistance,duration:50000,amplifier:9,show_particles:0b}],HandItems:[{id:netherite_sword,tag:{Unbreakable:1,CustomModelData:1,AttributeModifiers:[{AttributeName:"generic.attack_speed",Amount:40,Name:"generic.attack_speed",UUID:[I;-1231021,14397,111025,-28794]},{AttributeName:"generic.attack_damage",Amount:75,Name:"generic.attack_damage",UUID:[I;-1231021,14497,111025,-28994]}],Enchantments:[{id:vanishing_curse,lvl:1},{id:sharpness,lvl:5}]},Count:1},{id:netherite_sword,tag:{Unbreakable:1,CustomModelData:1,AttributeModifiers:[{AttributeName:"generic.attack_speed",Amount:40,Name:"generic.attack_speed",UUID:[I;-1231021,14397,111025,-28794]},{AttributeName:"generic.attack_damage",Amount:75,Name:"generic.attack_damage",UUID:[I;-1231021,14497,111025,-28994]}],Enchantments:[{id:vanishing_curse,lvl:1},{id:sharpness,lvl:5}]},Count:1}],ArmorItems:[{id:netherite_boots,tag:{Trim:{pattern:silence,material:gold},Enchantments:[{lvl:4,id:projectile_protection},{lvl:5,id:protection},{lvl:3,id:thorns},{lvl:1,id:vanishing_curse}],AttributeModifiers:[{AttributeName:"generic.armor",Amount:15,Name:"generic.armor",UUID:[I;-1231021,38018,121121,-76036]},{AttributeName:"generic.armor_toughness",Amount:8,Name:"generic.armor_toughness",UUID:[I;-1231021,38318,121121,-76636]}]},Count:1},{id:netherite_leggings,tag:{Trim:{pattern:silence,material:gold},Enchantments:[{lvl:4,id:projectile_protection},{lvl:5,id:protection},{lvl:3,id:thorns},{lvl:1,id:vanishing_curse}],AttributeModifiers:[{AttributeName:"generic.armor",Amount:15,Name:"generic.armor",UUID:[I;-1231021,38018,121121,-76036]},{AttributeName:"generic.armor_toughness",Amount:8,Name:"generic.armor_toughness",UUID:[I;-1231021,38318,121121,-76636]}]},Count:1},{id:netherite_chestplate,tag:{Trim:{pattern:silence,material:gold},Enchantments:[{lvl:4,id:projectile_protection},{lvl:5,id:protection},{lvl:3,id:thorns},{lvl:1,id:vanishing_curse}],AttributeModifiers:[{AttributeName:"generic.armor",Amount:15,Name:"generic.armor",UUID:[I;-1231021,38018,121121,-76036]},{AttributeName:"generic.armor_toughness",Amount:8,Name:"generic.armor_toughness",UUID:[I;-1231021,38318,121121,-76636]}]},Count:1},{id:netherite_helmet,tag:{Trim:{pattern:silence,material:gold},Enchantments:[{lvl:4,id:projectile_protection},{lvl:5,id:protection},{lvl:3,id:thorns},{lvl:1,id:vanishing_curse}],AttributeModifiers:[{AttributeName:"generic.armor",Amount:15,Name:"generic.armor",UUID:[I;-1231021,38018,121121,-76036]},{AttributeName:"generic.armor_toughness",Amount:8,Name:"generic.armor_toughness",UUID:[I;-1231021,38318,121121,-76636]}]},Count:1}],Attributes:[{Name:"generic.attack_speed",Base:81f},{Name:"generic.movement_speed",Base:0.5f},{Name:"generic.max_health",Base:3000f}],HandDropChances:[0f,0f],ArmorDropChances:[0f,0f,0f,0f]}]}
```
