### ISSUE TITLE
Mob Arena reformulação de melhorias

### ISSUE THREAD

**Issue by ghost** [leogianfagna/IssueTracker#804]
### Servidor afetado

Ausevento

### Qual o propósito da ideia?

Tornar mais intuitivo receber as recompensas

### Descrição da ideia

# Ideia: 
Simplificar o processo de resgate com uma saída que executa esses dois comandos (placa de pressão) ou fornecer instruções mais claras e destacadas (A mensagem no meio da arena e facilmente ignorada por muitos players), com isso poderia ajudar a evitar que os jogadores fiquem perdidos ou frustrados.

![image](https://github.com/user-attachments/assets/4637bae1-49ca-4902-9c50-a83f34e508af)

### Aplicação

Em um dos lados da arena, na área destinada aos jogadores que já foram eliminados, construir uma estrutura (Porta) que sirva tanto como ponto de saída quanto para coletar as moedas.
Levando o jogador de volta à central AusEvento de forma simples e sem complicações.

# To-do
- [x] Sistema interativo entre todos os servidores que resgata o valor de doação pelo MySQL
- [x] Reformulação na forma que é iniciada a mob arena para evitar bugs. Esse final de semana muitas vezes não foram iniciadas
- [x] Simplificar o processo de resgate de recompensas onde apenas um comando resgata as recompensas e sai automaticamente
